### ISSUE TITLE
Save protected files

### ISSUE THREAD

**Issue by jdbancal** [EPFL-ENAC/ENACrestic#4]
I would like to backup important configuration files present in the folder `/etc`, but `restic` complains that
```
! error: Open: open /etc/filename: permission denied
```
Any ways of achieving this with `ENACrestic`?

**Comment by sbancal** [comment]
Thanks for the question.

I don't see a way to implement this in a clean and transparent way for the end user.

First, I'd say that ENACrestic is designed to do a **user data backup** in contrast to a **system backup**.

If we really want this to work, the `restic` itself would have to be run as *root*. For security reasons it would mean that the end user will have to type his password into ENACrestic every time he opens a session.
This would be contrary to the principle chosen for ENACrestic that it has to be run automatically and transparently so that the user doesn't care about it.

An alternative would be to grant read access to the local user on all the files you want to backup.

Hope this helps.

Regards,

**Comment by jdbancal** [comment]
Al right, I see why this would be out of scope. Thanks for the explanation!
